"""add custom_prompt to characters

Revision ID: 151ed9f939d3
Revises: 1bb26fd69ac5
Create Date: 2026-04-03 06:04:20.060801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '151ed9f939d3'
down_revision: Union[str, Sequence[str], None] = '1bb26fd69ac5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('custom_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'custom_prompt')
    # ### end Alembic commands ###
