"""add_progress_and_summary_to_study_plans

Revision ID: 1bb26fd69ac5
Revises: 1cda804661df
Create Date: 2026-04-03 05:12:05.362823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bb26fd69ac5'
down_revision: Union[str, Sequence[str], None] = '1cda804661df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_plans', sa.Column('ai_plan_summary', sa.Text(), nullable=True))
    op.add_column('study_plans', sa.Column('task_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('study_plans', sa.Column('completed_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_plans', 'completed_count')
    op.drop_column('study_plans', 'task_count')
    op.drop_column('study_plans', 'ai_plan_summary')
    # ### end Alembic commands ###
