"""add_current_situation_to_study_plans

Revision ID: 1cda804661df
Revises: d286c1b1b2d8
Create Date: 2026-04-03 04:44:20.158622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cda804661df'
down_revision: Union[str, Sequence[str], None] = 'd286c1b1b2d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_plans', sa.Column('current_situation', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_plans', 'current_situation')
    # ### end Alembic commands ###
