"""add avatar_url to characters

Revision ID: 3bd26a0eab09
Revises: 151ed9f939d3
Create Date: 2026-04-03 06:13:12.276574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bd26a0eab09'
down_revision: Union[str, Sequence[str], None] = '151ed9f939d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('avatar_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'avatar_url')
    # ### end Alembic commands ###
