"""add login_streak affection to users, avatar_url custom_prompt to characters

Revision ID: fc4116029079
Revises: 3bd26a0eab09
Create Date: 2026-04-03 12:42:45.797900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc4116029079'
down_revision: Union[str, Sequence[str], None] = '3bd26a0eab09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('login_streak', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('affection', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'affection')
    op.drop_column('users', 'login_streak')
    op.drop_column('users', 'last_login_date')
    # ### end Alembic commands ###
